using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.SqlClient;
using System.Diagnostics;
using System.Drawing.Printing;
using Outlook = Microsoft.Office.Interop.Outlook;

namespace KPIAnalyser
{



    public partial class frmViewQuotationItems : Form
    {


        public string _startDate { get; set; }
        public string _endDate { get; set; }
        public string _staffName { get; set; }

        public string _doorType { get; set; }


        public frmViewQuotationItems(string startDate, string endDate, string staffName, string doorType)
        {
            InitializeComponent();
            _startDate = startDate;
            _endDate = endDate;
            _staffName = staffName;
            _doorType = doorType;
          


        populateGrid();
           
            lblName.Text = "Items quoted by: " + staffName;
            lblStart.Text = "Start Date: " + startDate;
            lblEnd.Text = "End Date:  " + endDate;
            lblDoorTypes.Text = "Door Type: " + doorType;
         
        }

        private void populateGrid()
        {
            SqlConnection conn = new SqlConnection(ConnectionStrings.ConnectionString);

            conn.Open();


            SqlCommand cmd = new SqlCommand("usp_kpi_quotation_list", conn);
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.Parameters.Add("@startDate", SqlDbType.NVarChar).Value = _startDate;
            cmd.Parameters.Add("@endDate", SqlDbType.NVarChar).Value = _endDate;
            cmd.Parameters.Add("@staffName", SqlDbType.NVarChar).Value = _staffName;
            cmd.Parameters.Add("@doorType", SqlDbType.NVarChar).Value = _doorType;
            
            

            SqlDataAdapter da = new SqlDataAdapter(cmd);
            DataTable dt = new DataTable();

            da.Fill(dt);
            dataGridView1.DataSource = dt;
            dataGridView1.Refresh();
            conn.Close();
        }


        private void DataGridView1_CellDoubleClick(object sender, DataGridViewCellEventArgs e)
        {

           

        }

        private void FrmViewQuotationItems_Load(object sender, EventArgs e)
        {
            // TODO: This line of code loads data into the 'order_databaseDataSet.view_solidworks_quoted_door_types' table. You can move, or remove it, as needed.
            this.view_solidworks_quoted_door_typesTableAdapter.Fill(this.order_databaseDataSet.view_solidworks_quoted_door_types);

        }


        private void printImage()
        {
            try
            {
                PrintDocument pd = new PrintDocument();
                pd.PrintPage += (sender, args) =>
                {
                    System.Drawing.Image i = System.Drawing.Image.FromFile(@"C:\temp\temp2.jpg");
                    Point p = new Point(100, 100);
                    args.Graphics.DrawImage(i, args.MarginBounds);

                };

                pd.DefaultPageSettings.Landscape = true;
                Margins margins = new Margins(50, 50, 50, 50);
                pd.DefaultPageSettings.Margins = margins;
                pd.Print();
            }
            catch
            {

            }
        }

        private void DataGridView1_CellDoubleClick_1(object sender, DataGridViewCellEventArgs e)
        {
             try
            {
                int rowindex = dataGridView1.CurrentCell.RowIndex;


                int quoteID = Convert.ToInt32(dataGridView1.Rows[rowindex].Cells[0].Value.ToString());
                int itemID = Convert.ToInt32(dataGridView1.Rows[rowindex].Cells[1].Value.ToString());
                int revID = Convert.ToInt32(dataGridView1.Rows[rowindex].Cells[2].Value.ToString());

                string quotationLocation = @"\\designsvr1\solidworks\Door Designer\Specifications\Project " + quoteID.ToString() + @"\\Quotations\Revision " + revID.ToString() + @"\\Quotation" + quoteID.ToString() + "-" + itemID.ToString() + "-" + revID.ToString() + ".pdf";


                Process.Start(quotationLocation);


            }

            catch

            {

                MessageBox.Show("This document has not yet been generated by driveworks, please try again later", "Try again later", MessageBoxButtons.OK, MessageBoxIcon.Information);

            }

        }

        private void BtnPrint_Click(object sender, EventArgs e)
        {
            try
            {
                System.Drawing.Image bit = new Bitmap(Screen.PrimaryScreen.WorkingArea.Width, Screen.PrimaryScreen.WorkingArea.Height);

                Graphics gs = Graphics.FromImage(bit);

                gs.CopyFromScreen(new Point(0, 0), new Point(0, 0), bit.Size);

                bit.Save(@"C:\temp\temp2.jpg");

                printImage();
            }
            catch
            {

            }
        }

        private void BtnEmail_Click(object sender, EventArgs e)
        {
            try
            {
                System.Drawing.Image bit = new Bitmap(Screen.PrimaryScreen.WorkingArea.Width, Screen.PrimaryScreen.WorkingArea.Height);

                Graphics gs = Graphics.FromImage(bit);

                gs.CopyFromScreen(new Point(0, 0), new Point(0, 0), bit.Size);

                bit.Save(@"C:\temp\temp2.jpg");


            }
            catch
            {

            }





            Outlook.Application outlookApp = new Outlook.Application();
            Outlook.MailItem mailItem = outlookApp.CreateItem(Outlook.OlItemType.olMailItem);
            mailItem.Subject = "";
            mailItem.To = "";
            string imageSrc = @"C:\Temp\temp2.jpg"; // Change path as needed

            var attachments = mailItem.Attachments;
            var attachment = attachments.Add(imageSrc);
            attachment.PropertyAccessor.SetProperty("http://schemas.microsoft.com/mapi/proptag/0x370E001F", "image/jpeg");
            attachment.PropertyAccessor.SetProperty("http://schemas.microsoft.com/mapi/proptag/0x3712001F", "myident"); // Image identifier found in the HTML code right after cid. Can be anything.
            mailItem.PropertyAccessor.SetProperty("http://schemas.microsoft.com/mapi/id/{00062008-0000-0000-C000-000000000046}/8514000B", true);

            // Set body format to HTML

            mailItem.BodyFormat = Outlook.OlBodyFormat.olFormatHTML;
            mailItem.Attachments.Add(imageSrc);
            string msgHTMLBody = "";
            mailItem.HTMLBody = msgHTMLBody;
            mailItem.Display(true);
        }

        private void DataGridView1_CellContentClick(object sender, DataGridViewCellEventArgs e)
        {

        }

        private void CmbDoorType_SelectedIndexChanged(object sender, EventArgs e)
        {
            populateGrid();
        }

        private void CmbDoorType_SelectedValueChanged(object sender, EventArgs e)
        {
       
        }

        private void BtnRefresh_Click(object sender, EventArgs e)
        {
            populateGrid();
        }

        private void BtnEmailItem_Click(object sender, EventArgs e)
        {


            var attachmentList = new List<string>();

            string attachmentLocation = "";



            Outlook.Application outlookApp = new Outlook.Application();
            Outlook.MailItem mailItem = outlookApp.CreateItem(Outlook.OlItemType.olMailItem);
            mailItem.Subject = "";
            mailItem.To = "";


            foreach (DataGridViewRow r in dataGridView1.SelectedRows)
            {

                int rowindex = r.Index;

                int quoteID = Convert.ToInt32(dataGridView1.Rows[rowindex].Cells[0].Value.ToString());
                int itemID = Convert.ToInt32(dataGridView1.Rows[rowindex].Cells[1].Value.ToString());
                int revID = Convert.ToInt32(dataGridView1.Rows[rowindex].Cells[2].Value.ToString());

                attachmentLocation = @"\\designsvr1\solidworks\Door Designer\Specifications\Project " + quoteID.ToString() + @"\\Quotations\Revision " + revID.ToString() + @"\\Quotation" + quoteID.ToString() + "-" + itemID.ToString() + "-" + revID.ToString() + ".pdf";

                var attachments = mailItem.Attachments;
                var attachment = attachments.Add(attachmentLocation);
                mailItem.Attachments.Add(attachmentLocation);
                attachment.PropertyAccessor.SetProperty("http://schemas.microsoft.com/mapi/proptag/0x370E001F", "image/jpeg");
                attachment.PropertyAccessor.SetProperty("http://schemas.microsoft.com/mapi/proptag/0x3712001F", "myident"); // Image identifier found in the HTML code right after cid. Can be anything.
                mailItem.PropertyAccessor.SetProperty("http://schemas.microsoft.com/mapi/id/{00062008-0000-0000-C000-000000000046}/8514000B", true);

            }





            





            // Set body format to HTML

            mailItem.BodyFormat = Outlook.OlBodyFormat.olFormatHTML;

            foreach (var attachmentGrab in attachmentList)
            {
                
            }



           
            string msgHTMLBody = "";
            mailItem.HTMLBody = msgHTMLBody;
            mailItem.Display(true);

            try
            {


                mailItem.HTMLBody = "" + mailItem.HTMLBody;


            }

            catch

            {

               // MessageBox.Show("This document has not yet been generated by driveworks, please try again later", "Try again later", MessageBoxButtons.OK, MessageBoxIcon.Information);

            }
        }
    }
}
